version: '2'
services: 
        ei-inference:
                build: ./ei-inference
                privileged: true
                restart: always
                
                labels:
                        io.balena.features.dbus: '1'
                        io.balena.features.kernel-modules: '1'
                volumes: 
                        - 'shared-data:/var/data'
                        - 'shared-media:/var/media'
                environment:
                        - UDEV=1
                devices:
                        - '/dev:/dev'
                ports: 
                        - 4912
        wifi-connect:
                build: ./wifi-connect
                restart: always
                network_mode: host
                privileged: true
                labels:
                        io.balena.features.dbus: '1'
                        io.balena.features.firmware: '1'
                cap_add:
                        - NET_ADMIN
                environment:
                        DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"

volumes:
        shared-data:
        shared-media:
        