version: '2'
services: 
  ei-inference:
        build: ./ei-inference
        privileged: true
        restart: always
        
        labels:
                io.balena.features.dbus: '1'
                io.balena.features.kernel-modules: '1'
        volumes: 
                - 'shared-data:/var/data'
                - 'shared-media:/var/media'
        environment:
                - UDEV=1
        devices:
                - '/dev:/dev'
        ports: 
                - 4912

volumes:
        shared-data:
        shared-media:
        